### ISSUE TITLE
NameError: global name 'PACKAGE_NAME' is not defined

### ISSUE THREAD

**Issue by tyilo** [relikd/Plist-Binary_sublime#1]
After installing this package with package control and trying to go from a binary plist to XML format, I get the following error:

```
Traceback (most recent call last):
  File "./Plist Binary.py", line 9, in run_
NameError: global name 'PACKAGE_NAME' is not defined
```

**Comment by relikd** [comment]
can't reproduce. Have you tried another plist? Does it complain with other plugins? Sublime Text 2 or the new Sublime Text 3? Does the command "plutil -convert xml1 myPlist.plist" work in Terminal?

**Comment by axmo** [comment]
Here as well:

```
Traceback (most recent call last):
  File "Plist Binary in /Users/<username>/Library/Application Support/Sublime Text 3/Installed Packages/Plist Binary.sublime-package", line 9, in run_
NameError: global name 'PACKAGE_NAME' is not defined
```

Installed through Package Control on Sublime Text 3.

Package version: 2013.10.05.13.48.19

The command `plutil -convert xml1 <path-to-plist>` works in Terminal.

**Comment by relikd** [comment]
removed that constant, should work now.
